version: '3'

services:

  nginx:
    container_name: phc_lks_test_nginx
    image: nginx:1.15.8-alpine
    restart: always
    depends_on:
      - backend
    volumes:
      - ./storage:/storage
      - ./nginx.conf.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - "6363:80"

  redis:
    container_name: phc_lks_test_redis
    image: redis:5.0-rc6-alpine
    restart: always
    env_file: .env
    ports:
      - "26379:6379"

  postgresql:
    container_name: phc_lks_test_postgres
    image: postgres:11.1-alpine
    restart: always
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    container_name: phc_lks_test_backend
    image: 63phc/lks:latest
    restart: always
    volumes:
      - ./storage:/storage
    env_file: .env
    depends_on:
      - postgresql
      - redis
