sudo: required
dist: trusty
language: bash
services: docker
env:
  - DOCKER_COMPOSE_VERSION=1.17.1
before_install:
  - openssl aes-256-cbc -K $encrypted_4d7713304c46_key -iv $encrypted_4d7713304c46_iv -in id_rsa.enc -out id_rsa -d
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
script:
  - docker-compose -f docker/docker-compose.build.yml build
  - docker-compose -f docker/docker-compose.build.yml push
before_deploy:
  - mkdir -p ~/.ssh
  - SSH_PRIVATE_KEY=$(cat id_rsa)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - ssh-keyscan -H 'travis-ci.com' >> ~/.ssh/known_hosts
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chmod +x ./docker/deploy.sh
deploy:
  provider: script
  script: REMOTE_HOST=$REMOTE_HOST REMOTE_USER=lks PROJECT_DIR=/home/lks PROJECT_PROFILE=prod bash ./docker/deploy.sh
  on:
    branch: develop
