language: python
stages:
  - compile
  - test
  - deploy

sudo: required
dist: trusty

services:
  - docker

install:
  - docker-compose pull
  - docker-compose build

#script:
#  - docker-compose run -e DJANGO_SETTINGS_MODULE=djangodocker.settings.testing --no-deps --rm app py.test

deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      branch: master
    skip_cleanup: true
