sudo: required
dist: trusty

services:
  - docker

install:
  - docker-compose -f docker/docker-compose.dev.yml pull
  - docker-compose -f docker/docker-compose.dev.yml build

#script:
#  - docker-compose run -e DJANGO_SETTINGS_MODULE=djangodocker.settings.testing --no-deps --rm app py.test

deploy:
  - provider: script
    script: bash docker/deploy.sh
    on:
      branch: master
    skip_cleanup: true
