version: '2'

services:
  # Storage container
  storage:
    container_name: storage
    build:
      context: ..
      dockerfile: /storage/Dockerfile
    volumes:
      - ./storage:/storage
      - ./storage/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3001:80"
