version: '2'

services:

  redis:
    image: redis:5.0-rc6-alpine
    container_name: phc_lks_redis
    env_file:
      - ./dev/.env
    ports:
      - "6379:6379"

  postgresql:
    image: postgres:11-alpine
    container_name: phc_lks_postgres
    env_file:
      - ./dev/.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main

  backend:
    build:
      context: ..
      dockerfile: 63phc/lks:lates
    container_name: phc_lks_backend
    env_file:
      - ./dev/.env
    command: /run_project.sh
    links:
      - postgresql
      - redis
    depends_on:
      - postgresql
      - redis
    expose:
      - 22
      - 8000
    ports:
      - "8000:8000"
      - "0.0.0.0:7777:22"
    networks:
      - main

  storage:
    container_name: storage
    build:
      context: ..
      dockerfile: /docker/dev/storage/Dockerfile
    volumes:
      - ./storage:/storage
      - ./storage/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3001:80"
    networks:
      - main

networks:
  main:
