version: '3'

services:

  nginx:
    container_name: phc_lks_dev_nginx
    image: nginx:1.17.6-alpine
    restart: always
    depends_on:
      - backend
    volumes:
      - ./static:/static
      - ./media:/media
      - ./nginx.conf.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - "26363:80"

  redis:
    container_name: phc_lks_dev_redis
    image: redis:6.0-rc1-alpine
    restart: always
    env_file: .env

  postgresql:
    container_name: phc_lks_devt_postgres
    image: postgres:12.1-alpine
    restart: always
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  backend:
    container_name: phc_lks_dev_backend
    image: docker.pkg.github.com/63phc/lks/test_dev:0.2
#    build:
#      context: ../
#      dockerfile: .docker/Dockerfile
    restart: always
    command: bash -c "
      gunicorn src.core.wsgi:application -w 2 -b 0.0.0.0:8000"

    volumes:
      - ./static:/app/static
      - ./media:/app/media
    env_file: .env
    depends_on:
      - postgresql
      - redis