version: '3'

services:

  nginx:
    container_name: lks_${DJANGO_ENV}_nginx
    image: nginx:1.19.5-alpine
    restart: always
    depends_on:
      - backend
    volumes:
      - ./static:/static
      - ./media:/media
      - ./nginx.conf.nginx:/etc/nginx/conf.d/default.conf
    env_file: .env
    ports:
      - "${NGINX_PORT}:80"

  redis:
    container_name: lks_${DJANGO_ENV}_redis
    image: redis:6.0.9-alpine
    restart: always
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}

  postgresql:
    container_name: lks_${DJANGO_ENV}_postgres
    image: postgres:13.1-alpine
    restart: always
    env_file: .env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data

  backend:
    container_name: lks_${DJANGO_ENV}_backend
    image: 63phc/lks:latest
    build:
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        env: dev
    restart: always
    command: bash -c "
      gunicorn src.core.wsgi:application -w 2 -b 0.0.0.0:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    env_file: .env
    depends_on:
      - postgresql
      - redis

  celery:
    container_name: lks_${DJANGO_ENV}_celery
    image: 63phc/lks:latest
    restart: always
    command: bash -c "
      celery -A src.core.celery worker --loglevel=info"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    env_file: .env
    depends_on:
      - postgresql
      - redis
