version: "3.7"

services:
  postgresql:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_NAME=lks_pg_name
      - POSTGRES_USER=lks_pg_user
      - POSTGRES_DB=lks_pg_db
      - POSTGRES_PASSWORD=lks_pg_pass
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./data/pgdata_3:/var/lib/postgresql/data/pgdata

  redis:
    image: redis:6.0.9-alpine
    ports:
      - "6379:6379"
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD}

#  redis-commander:
#    image: rediscommander/redis-commander:latest
#    environment:
#      - REDIS_HOSTS=local:redis:6379
#      - HTTP_USER=root
#      - HTTP_PASSWORD=qwerty
#    ports:
#      - 8081:8081
#    depends_on:
#      - redis
#
#  flower:
#    container_name: phc_lks_${PROFILE}_flower
#    image: mher/flower
#    command: ["--app src.celery",
#              "--broker=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}/2",
#              "--port=${FLOWER_PORT}",
#              "--basic_auth=${FLOWER_USER}:${FLOWER_PASSWORD}"]
#    depends_on:
#      - redis
#    ports:
#      - "${FLOWER_PORT}:5555"
#
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
#    container_name: elasticsearch
#    environment:
#      - node.name=elasticsearch
#      - network.host=0.0.0.0
#      - cluster.name=es-docker-cluster
#      - bootstrap.memory_lock=true
#      - discovery.type=single-node
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    volumes:
#      - ./data/elasticsearch:/usr/share/elasticsearch/data
#      - ./data/elasticsearch/log:/dev/log
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.10.1
#    container_name: kibana
#    environment:
#      - SERVER_HOST="0"
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
#      - XPACK_SECURITY_ENABLED=false
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch