# Generated by Django 2.1.2 on 2018-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_regenerate_user_address_hashes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr')], max_length=64, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('line1', models.CharField(max_length=255, verbose_name='First line of address')),
                ('line2', models.CharField(blank=True, max_length=255, verbose_name='Second line of address')),
                ('line3', models.CharField(blank=True, max_length=255, verbose_name='Third line of address')),
                ('line4', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='State/County')),
                ('postcode', models.CharField(blank=True, max_length=64, verbose_name='Post/Zip-code')),
                ('search_text', models.TextField(editable=False, verbose_name='Search text - used only for searching addresses')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='id',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='line1',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='line2',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='line3',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='line4',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='search_text',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='title',
        ),
    ]
