name: build
on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: self-hosted
    steps:

    - uses: actions/checkout@master

    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        DEV: True
      with:
        name: ${{ secrets.DOCKER_REPO }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: .docker/Dockerfile
        workdir: .
        tag_semver: true
        buildargs: DEV

    - name: Bump version
      run: |
        bump2version --new-version 0.0.1  --verbose --allow-dirty part
#          bump2version patch --verbose --allow-dirty

  deploy:
    - name: Docker down, pull and up remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd ${{ secrets.PATH_BACKEND }}
          docker-compose down
          docker-compose pull
          docker-compose up -d
