name: build
on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
    - name: Bump version
    - run: pip install bump2version
#    - run: bump2version patch --verbose --allow-dirty

    - name: Get release version
    - run: echo ::set-env name=VERSION::$(echo $(bump2version patch --verbose --allow-dirty) | tail -c 7)

    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        DEV: True
      with:
        name: ${{ secrets.DOCKER_REPO }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: .docker/Dockerfile
        workdir: .
#        tag_semver: true
        buildargs: DEV
        tags: "latest,${{ env.VERSION }}"

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Docker down, pull and up remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd ${{ secrets.PATH_BACKEND }}
          docker-compose down
          docker-compose pull
          docker-compose up -d
