name: build
on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@2.7
      env:
        TEST_VAR: ${{ secrets.PATH_BACKEND }}
      with:
        if: startsWith(github.ref, 'refs/tags/*')
        name: ${{ secrets.DOCKER_REPO }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: .docker/Dockerfile
        #        tags: ${{ github.ref }}:${{ }}
        snapshot: true
        cache: true
        workdir: .
        buildargs: TEST_VAR
        tag_semver: true
