name: build
on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@2.7
      env:
        TEST_VAR: ${{ secrets.PATH_BACKEND }}
      with:
#        if: startsWith(github.ref, 'refs/heads/tags/v')
        name: ${{ secrets.DOCKER_REPO }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: .docker/Dockerfile
        tags: "jopa"
#        snapshot: true
#        cache: true
        workdir: .
        buildargs: TEST_VAR
#        tag_semver: true

#  deploy:
#    runs-on: self-hosted
#    steps:
#      - name: Copy file remote host
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.HOST_USERNAME }}
#          password: ${{ secrets.HOST_PASSWORD }}
#          source: ".docker/docker-compose.yml,.docker/nginx.conf.nginx, .docker/.env.example"
#          target: "${{ secrets.PATH_BACKEND }}"
#          strip_components: 1

#      - name: Docker down, pull and up remote host
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.HOST_USERNAME }}
#          password: ${{ secrets.HOST_PASSWORD }}
#          script: |
#            cd ${{ secrets.PATH_BACKEND }}
#            docker-compose down
#            docker-compose pull
#            docker-compose up -d
