name: build
on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        TEST_VAR: ${{ secrets.PATH_BACKEND }}
      with:
        name: ${{ secrets.DOCKER_REPO }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: .docker/Dockerfile
        tags: "${{ github.ref }}:1.0, latest"
#        snapshot: true
#        cache: true
        workdir: .
        buildargs: TEST_VAR
#        tag_semver: true

#  deploy:
#      - name: Docker down, pull and up remote host
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.HOST }}
#          username: ${{ secrets.HOST_USERNAME }}
#          password: ${{ secrets.HOST_PASSWORD }}
#          script: |
#            cd ${{ secrets.PATH_BACKEND }}
#            docker-compose down
#            docker-compose pull
#            docker-compose up -d
