name: Deploy
on:
  push:
    branches:
      - 'develop'

jobs:
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Copy file remote host
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        source: ".docker/docker-compose.yml,.docker/nginx.conf.nginx, .docker/.env.example"
        target: "${{ secrets.PATH_BACKEND }}"
        strip_components: 1

    - name: Docker down, pull and up remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd ${{ secrets.PATH_BACKEND }}
          docker-compose down
          docker-compose pull
          docker-compose up -d


