name: Build and Publish Docker
on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@2.7
      env:
        DEV: dev
        TEST_VAR: ${{ secrets.TEST_VAR }}
      with:
        name: ${{ secrets.DOCKER_REPO }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest,${{ github.ref }}
        workdir: .
        dockerfile: .docker/Dockerfile
        buildargs: DEV,TEST_VAR

    - name: Down docker remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd ${{ secrets.PATH_BACKEND }}
          docker-compose down

    - name: Pull docker remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd ${{ secrets.PATH_BACKEND }}
          docker-compose pull
          docker-compose up -d

    - name: Up -d docker remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd ${{ secrets.PATH_BACKEND }}
          docker-compose up -d