name: develop
on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@2.7
      env:
        DEV: dev_arg
        TEST_VAR: ${{ secrets.TEST_VAR }}
      with:
        name: ${{ secrets.DOCKER_REPO }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: latest,${{ github.ref }}
        workdir: .
        dockerfile: .docker/Dockerfile
        buildargs: DEV,TEST_VAR

    - name: Copy LICENSE
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "LICENSE"
        target: ${{ secrets.PATH_BACKEND }}

    - name: Down Pull Up docker remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd ${{ secrets.PATH_BACKEND }}
          docker-compose down
          docker-compose pull
          docker-compose up -d


