name: echo
on:
  push:
    branches:
      - 'develop'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: echo
        env:
          TEST_VAR: ${{ toJson(github) }}
          REV: ${{ github.ref }}
        run: |
          echo "$TEST_VAR"
          echo "$REV"
          echo " $GITHUB_REF "
          echo $GITHUB_REF
