name: prod-build
on:
  push:
    branches:
      - 'master'

jobs:
  prod-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
      - run: pip install bump2version

      - name: Set VERSION
        run: |
          echo ::set-env name=VERSION::$(echo $(bump2version minor --verbose --allow-dirty) | tail -c 7)
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "[minor]"
          git push --force origin HEAD:$GITHUB_REF

      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          REQUIREMENT: development
        with:
          name: ${{ secrets.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: .docker/Dockerfile
          workdir: .
          buildargs: REQUIREMENT
          tags: "latest,${{ env.VERSION }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Docker down, pull and up remote host
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd ${{ secrets.PATH_BACKEND_PROD }}
          docker-compose down
          docker-compose pull
          docker-compose up -d

  pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: ${{ secrets.PIPY_USER }}
        password: ${{ secrets.PIPY_PASS }}