name: remote ssh command
on:
  push:
    branches:
      - 'develop'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        script: |
          cd /home/lks/dev
          ls -al
          docker-compose pull
          docker-compose down
          docker-compose up -d