name: tests
on: [push]

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements/test.txt
      - name: Run pytests
        run:  DJANGO_ENV=test pytest
      - name: Tests report
        run: coverage report
