name: tests
on:
  push:
    branches:
      - 'develop'
      - 'master'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r src/requirements/test.txt
      - name: Run pytests
        run: pytest
      - name: Tests report
        run: coverage report
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
